name: CMake Build Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug
  BUILD_TESTS: true
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
  VCPKG_BUILTIN_BASELINE: c8696863d371ab7f46e213d8f5ca923c4aef2a00
  VCPKG_ENABLE_METRICS: 1
  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/vcpkg/bincache
  VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'
  OUTPUT_DIRECTORY: out/build

permissions:
  actions: read
  deployments: write
  contents: write
  id-token: write
  security-events: write

jobs:
  setup_environment:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ] # , ubuntu-latest, macos-latest

    steps:
      - name: Checkout & Init Submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest

      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: latest
          vulkan-components: Vulkan-Headers
          vulkan-use-cache: true

      - name: Inspect Root Directory
        if: matrix.os == 'windows-latest'
        working-directory: ${{github.workspace}}
        run: ls

      - name: Configure and Build Project
        run: |
          mkdir -p ${{env.OUTPUT_DIRECTORY}}/${{env.BUILD_TYPE}}
          cmake --build --preset ${{env.BUILD_TYPE}}
